package margit;

import java.io.IOException;
import java.util.Collections;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;
import javafx.scene.shape.Circle;

/** Represents one chat message with a speaker avatar. */
public class DialogBox extends HBox {
    private static final double DIALOG_WIDTH_RATIO = 0.78;

    @FXML
    private Label dialog;
    @FXML
    private ImageView displayPicture;

    private DialogBox(String text, Image image) {
        FXMLLoader fxmlLoader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
        fxmlLoader.setController(this);
        fxmlLoader.setRoot(this);
        loadDialogView(fxmlLoader);

        dialog.setText(text);
        displayPicture.setImage(image);
        setMaxWidth(Double.MAX_VALUE);
        dialog.maxWidthProperty().bind(widthProperty().multiply(DIALOG_WIDTH_RATIO));
    }

    /**
     * Returns a right-aligned dialog box for a user message.
     *
     * @param text text submitted by the user
     * @return a dialog box without an avatar
     */
    public static DialogBox getUserDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, null);
        dialogBox.getStyleClass().add("user-dialog");
        dialogBox.displayPicture.setManaged(false);
        dialogBox.displayPicture.setVisible(false);
        return dialogBox;
    }

    /**
     * Returns a left-aligned dialog box for a Margit response.
     *
     * @param text response text generated by Margit
     * @param image Margit's avatar image
     * @param isError whether the response represents invalid input
     * @return a styled response dialog box
     */
    public static DialogBox getMargitDialog(String text, Image image, boolean isError) {
        DialogBox dialogBox = new DialogBox(text, image);
        dialogBox.getStyleClass().add(isError ? "error-dialog" : "margit-dialog");
        dialogBox.cropAvatarToCircle();
        dialogBox.flip();
        return dialogBox;
    }

    /** Reorders this dialog box so its avatar appears on the left. */
    private void flip() {
        ObservableList<Node> children = FXCollections.observableArrayList(getChildren());
        Collections.reverse(children);
        getChildren().setAll(children);
        setAlignment(Pos.TOP_LEFT);
    }

    /** Crops Margit's compact avatar into a circular crest. */
    private void cropAvatarToCircle() {
        Circle clip = new Circle(displayPicture.getFitWidth() / 2);
        clip.setCenterX(displayPicture.getFitWidth() / 2);
        clip.setCenterY(displayPicture.getFitHeight() / 2);
        displayPicture.setClip(clip);
    }

    /** Loads the dialog FXML view and reports a clear error if it cannot be read. */
    private void loadDialogView(FXMLLoader fxmlLoader) {
        try {
            fxmlLoader.load();
        } catch (IOException e) {
            throw new IllegalStateException("Unable to load a dialog box.", e);
        }
    }
}
